// This file is automatically generated. Do not edit it directly.
export const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || '';
// Support both common env names: VITE_SUPABASE_ANON_KEY (older) and VITE_SUPABASE_PUBLISHABLE_KEY (repo .env)
export const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || '';

import { createClient } from '@supabase/supabase-js';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});