// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frwejybzurvuvbusppak.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyd2VqeWJ6dXJ2dXZidXNwcGFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MzUyNjEsImV4cCI6MjA3MzExMTI2MX0.I31CqE6kFRrdh9ULjgPNyF2j6-W4GGhpCtaDqXIJTlk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});